boot.o: boot.S multiboot.h x86_desc.h types.h
paging.o: paging.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
IDT.o: IDT.c x86_desc.h types.h IDT.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h IDT.h
lib.o: lib.c lib.h types.h
paging.o: paging.c
rtc.o: rtc.c rtc.h lib.h types.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
